### ISSUE TITLE
Features for better lateral offset estimation

### ISSUE THREAD

**Issue by oterocoronel** [alihaydaroglu/suite3d#42]
When some planes have very little signal, the lateral shift estimation across planes is usually off. This is an issue with the data, not suite3d, but I think it could be handled better if one could:

1) Crop the recording before doing any motion correction (e.g. after job.run_init_pass). If the signal is too low for calculating the lateral offset in the mean images, then you probably won't get many neurons from there and could avoid creating a volume that you know has the wrong offsets for alignments

2) Make the x-y offset values accessible to the user to do some kind of basic adjustment. I've seen that the x-y offsets for planes 15-22 are reliable, but for planes 22-30 are sometimes off, I would be curious if I just use a linear interpolation from 15-22 extended to planes 22-30 if I can get anything from there

I thought about this when I noticed that in one recording the lateral-shift estimation was ~300pix for X and Y in a bad plane, thus creating a massively large recording (went from 500x500pix to 800x800pix, which is 2.5x larger and mostly empty with nans) and the only thing I could do was crop it after doing motion correction through all the data

Somewhat related:

3) Could we do lateral offset estimation after doing motion correction? This could help increase the SNR of the mean frames that are used for the shift estimations and give better results.

**Comment by alihaydaroglu** [comment]
this has been improved in the new initial pass
