### ISSUE TITLE
Crash when running job.vis_vmap_sweep(sweep_summary)

### ISSUE THREAD

**Issue by oterocoronel** [alihaydaroglu/suite3d#43]
This is in the Vaziri-GPU machines:

<img width="525" alt="image" src="https://github.com/alihaydaroglu/s2p-lbm/assets/78885453/aa940925-a4d5-46cb-8049-fac79f2dc4b4">

Based on this post suggestion (https://stackoverflow.com/a/72090539), running these lines fixed the issue for me:

```
pip uninstall opencv-python
pip install opencv-python-headless
```

**Comment by alihaydaroglu** [comment]
created a standalone napari UI that can be run from a remote computer to visualize vmap summary
